(() => {
  'use strict';
  const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=v=>Number.isSafeInteger(v)?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v/100):'Awaiting final quote';
  const endpoint=new URL('../customer-portal/backend/api.php',location.href), cartKey='mirroriedled_storefront_cart_vnext';
  const allowed=['Custom Infinity Mirror','Address Sign or Mailbox'];
  let session={configured:false,authenticated:false,capabilities:{}}, drafts=[], orders=[], service={};
  const requests=new Map();
  function message(id,text,error=false){$(id).textContent=text;$(id).classList.toggle('error',error);}
  async function api(action,data,query={}){
    const url=new URL(endpoint);url.searchParams.set('action',action);for(const[k,v]of Object.entries(query))url.searchParams.set(k,v);
    const options={credentials:'same-origin',cache:'no-store',headers:{Accept:'application/json'}};
    let fp;
    if(data){options.method='POST';fp=action+JSON.stringify(data instanceof FormData?[...data.entries()].map(([k,v])=>[k,v instanceof File?[v.name,v.size,v.lastModified]:v]):data);if(!requests.has(fp))requests.set(fp,crypto.randomUUID());
      if(data instanceof FormData){data.set('csrf',session.csrf||'');data.set('requestKey',requests.get(fp));options.body=data;}
      else{options.headers['Content-Type']='application/json';options.body=JSON.stringify({...data,csrf:session.csrf,requestKey:requests.get(fp)});}}
    const r=await fetch(url,options);if(!(r.headers.get('Content-Type')||'').includes('application/json'))throw new Error('Customer ordering is being connected. Your design is saved on this device.');
    const result=await r.json();if(!r.ok||!result.ok)throw new Error(result.error||'This step could not be completed.');if(fp)requests.delete(fp);return result;
  }
  function loadDrafts(){try{const saved=JSON.parse(localStorage.getItem(cartKey)||sessionStorage.getItem('mirroriedled_quote_draft_v1')||'[]');drafts=Array.isArray(saved)?saved.filter(x=>allowed.includes(x.product)).slice(0,20):[];}catch{drafts=[];}renderDrafts();}
  function persistDrafts(){localStorage.setItem(cartKey,JSON.stringify(drafts));sessionStorage.setItem('mirroriedled_quote_draft_v1',JSON.stringify(drafts));renderDrafts();}
  function itemHtml(item){const sign=item.addressBuilder;return `<strong>${esc(item.product)}</strong>${esc(item.size)} in · quantity ${esc(item.quantity||1)}<br>${esc(item.artwork)}${sign?`<br>${esc(sign.font)} lettering · ${esc(sign.finish)} · ${esc(sign.color)} · ${esc(sign.lighting)} · ${esc(sign.mount)}`:`<br>${esc(item.lighting)} · ${esc(item.finish)}`}${item.notes?`<br>${esc(item.notes)}`:''}`;}
  function renderDrafts(){ $('draftItems').innerHTML=drafts.length?drafts.map((x,i)=>`<li>${itemHtml(x)}<button class="button" type="button" data-remove="${i}">Remove</button></li>`).join(''):'<li>Your next build starts in either product builder.</li>';for(const b of $('draftItems').querySelectorAll('[data-remove]'))b.addEventListener('click',()=>{drafts.splice(Number(b.dataset.remove),1);persistDrafts();});$('saveBuild').disabled=!session.authenticated||!session.capabilities.business||!drafts.length;}
  async function refreshSession(){session=await api('session');service=await api('commerce-status');$('signedIn').hidden=!session.authenticated;$('accountForms').hidden=session.authenticated;$('teamLink').hidden=!(session.user?.roles||[]).length;$('accountName').textContent=session.user?.name||'';$('accountEmail').textContent=session.user?.email||'';
    $('serviceStatus').textContent=!session.configured?'Customer accounts and online ordering are still being connected. You can save designs in the product builders.':!session.capabilities.business?'Build requests are being connected. Your designs remain saved on this device.':service.paymentsAvailable?(service.paymentMode==='test'?'Payment testing is active. This is a test checkout; no real order payment will be taken.':'Custom-build ordering is open. The team confirms your complete quote, artwork proof, shipping and production estimate before you pay.'):'Accounts and quote requests are available. Online payments are still being connected; no payment can be taken yet.';renderDrafts();}
  for(const name of 'AL AK AZ AR CA CO CT DE DC FL GA HI ID IL IN IA KS KY LA ME MD MA MI MN MS MO MT NE NV NH NJ NM NY NC ND OH OK OR PA RI SC SD TN TX UT VT VA WA WV WI WY'.split(' '))$('saveBuildForm').elements.state.add(new Option(name,name));
  $('showSignup').addEventListener('click',()=>{$('signupForm').hidden=false;$('loginForm').hidden=true;$('showSignup').classList.add('primary');$('showLogin').classList.remove('primary');});
  $('showLogin').addEventListener('click',()=>{$('signupForm').hidden=true;$('loginForm').hidden=false;$('showLogin').classList.add('primary');$('showSignup').classList.remove('primary');});
  function auth(form,action,data){form.addEventListener('submit',async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;message('accountMessage','Connecting your account…');try{await api(action,data());form.reset();await refreshSession();await refreshOrders();message('accountMessage','You are signed in.');}catch(error){message('accountMessage',error.message,true);}finally{b.disabled=false;}});}
  auth($('signupForm'),'signup',()=>({name:$('signupName').value,email:$('signupEmail').value,password:$('signupPassword').value,requestedPlan:'free'}));
  auth($('loginForm'),'login',()=>({email:$('loginEmail').value,password:$('loginPassword').value}));
  $('logout').addEventListener('click',async()=>{try{await api('logout',{});await refreshSession();orders=[];renderOrders();message('accountMessage','Signed out.');}catch(error){message('accountMessage',error.message,true);}});
  async function upload(orderId,file){const body=new FormData();body.set('orderId',orderId);body.set('purpose','artwork');body.set('file',file);return api('business-upload',body);}
  $('saveBuildForm').addEventListener('submit',async e=>{
    e.preventDefault();if(!session.authenticated||!drafts.length)return;const button=$('saveBuild');button.disabled=true;message('buildMessage','Saving your design and delivery details…');
    try{
      const items=JSON.parse(JSON.stringify(drafts));const files=[];
      for(const item of items.filter(x=>x.builderDraftId)){const d=await window.MirrorDraftStore.get(item.builderDraftId);if(!d?.maskBlob)throw new Error('Reopen the Infinity Mirror builder to restore your engraving image before saving this build.');files.push(new File([d.maskBlob],`Infinity-${item.id}-engraving.png`,{type:'image/png',lastModified:0}));if(d.originalBlob&&d.state?.artwork?.source==='upload')files.push(new File([d.originalBlob],`Infinity-${item.id}-original.${d.originalBlob.type==='image/jpeg'?'jpg':d.originalBlob.type==='image/webp'?'webp':'png'}`,{type:d.originalBlob.type,lastModified:0}));}
      const fingerprint=JSON.stringify(items);let pending;try{pending=JSON.parse(sessionStorage.getItem('mled_pending_build')||'null');}catch{}
      let orderId;
      if(pending?.fingerprint===fingerprint&&pending.userId===session.user.id)orderId=pending.orderId;
      else {const result=await api('business-request',{items});orderId=result.order.id;sessionStorage.setItem('mled_pending_build',JSON.stringify({fingerprint,userId:session.user.id,orderId,uploaded:0}));pending={uploaded:0};}
      for(let i=pending?.uploaded||0;i<files.length;i++){await upload(orderId,files[i]);sessionStorage.setItem('mled_pending_build',JSON.stringify({fingerprint,userId:session.user.id,orderId,uploaded:i+1}));}
      const address=Object.fromEntries(new FormData(e.target));await api('commerce-address',{orderId,address});drafts=[];persistDrafts();sessionStorage.removeItem('mled_pending_build');await refreshOrders();message('buildMessage',`Build ${orderId} saved. Your complete quote, shipping cost and production estimate will appear below after review.`);$('orders').scrollIntoView({behavior:'smooth'});
    }catch(error){message('buildMessage',error.message,true);}finally{renderDrafts();}
  });
  const labels={REQUESTED:'Final pricing in review',QUOTED:'Review your proof and quote',APPROVED:'Proof approved',READY:'Production scheduled',BUILDING:'In production',QC_HOLD:'Quality review',QC_PASSED:'Quality passed',FULFILLING:'Shipped / delivery recorded',COMPLETED:'Completed',CANCELLED:'Cancelled'};
  function termsHtml(offer){return `<div class="totals"><div><span>Complete custom build</span><strong>${money(offer.productCents)}</strong></div><div><span>Shipping</span><strong>${money(offer.shippingCents)}</strong></div><div class="total"><span>Product + shipping</span><strong>${money(offer.beforeTaxCents)}</strong></div></div><p class="fine">${esc(offer.tax)}</p><p><strong>Production:</strong> ${esc(offer.productionMinDays)}–${esc(offer.productionMaxDays)} business days.<br><strong>Shipping transit:</strong> ${esc(offer.transitMinDays)}–${esc(offer.transitMaxDays)} business days.</p><p class="fine">${esc(offer.productionStarts)} Quote valid through ${esc(new Date(offer.expiresAt*1000).toLocaleDateString())}.</p>`;}
  function renderOrders(){if(!session.authenticated){$('orderList').innerHTML='<p>Sign in to view your private orders.</p>';return;}$('orderList').innerHTML=orders.length?orders.map(order=>{
    const c=order.commerce||{},offer=c.offer,pay=c.payment,paid=pay?.state==='paid',review=pay?.state==='review',expired=offer&&offer.expiresAt<Date.now()/1000;
    const payReady=offer&&!expired&&order.status==='APPROVED'&&!paid&&!review&&service.paymentsAvailable;
    const address=c.address;
    return `<article class="order-card" data-order="${esc(order.id)}"><div class="order-top ${paid?'paid':''}"><span>${paid?'Payment confirmed':review?'Payment needs review':esc(labels[order.status]||order.status)}</span><span>${esc(order.id)}</span></div><ul class="items">${order.items.map(i=>`<li>${itemHtml(i)}</li>`).join('')}</ul>${address?`<p><strong>Ship to:</strong> ${esc(address.name)} · ${esc([address.line1,address.line2,address.city,address.state,address.postalCode].filter(Boolean).join(', '))}</p>`:'<p class="fine">Save a delivery address below so shipping can be quoted.</p>'}
    ${offer?termsHtml(offer):`<p><strong>Final quote:</strong> ${money(order.quoteCents)}</p><p class="fine">${order.quoteCents===null?'The team is confirming the selected materials and fabrication price. ':''}Shipping and the production estimate are awaiting review. Checkout opens when all details are confirmed.</p>`}
    ${order.proof?`<h3>Final artwork proof ${esc(order.proof.version)}</h3><p>${esc(order.proof.summary)}</p><div class="proof-links">${order.files.filter(f=>f.purpose==='proof'&&f.id===order.proof.file_id).map(f=>`<a href="${esc(new URL('../customer-portal/'+f.url,location.href))}" target="_blank" rel="noopener">Open proof: ${esc(f.name)}</a>`).join('')}</div>`:''}
    ${order.status==='QUOTED'?`<form class="approve"><label class="check"><input type="checkbox" required><span>I reviewed the final artwork proof and the quoted product price${offer?', shipping and production estimate':''}.</span></label><button class="button primary" type="submit">Approve proof & quote</button></form>`:''}
    ${paid?`<p><strong>Paid:</strong> ${money(Number(pay.paid_cents))} · tax ${money(Number(pay.tax_cents))}<br>Confirmed ${esc(new Date(Number(pay.paid_at)*1000).toLocaleString())}.</p><p class="fine">Your confirmed payment and order details are retained in this account. The team will update the timeline as your build progresses.</p>`:''}
    ${payReady?`<form class="pay"><label class="check"><input type="checkbox" required><span>I accept this quote and the production and shipping estimates. I will review the final tax and total before paying.</span></label><button class="button primary" type="submit">${service.paymentMode==='test'?'Open test checkout':'Continue to secure payment'}</button></form>`:''}
    ${offer&&!paid&&!review&&!service.paymentsAvailable?'<p class="fine">Payment connection is being finalized. No payment can be taken yet.</p>':''}${expired&&!paid?'<p class="fine">This quote expired. Contact us for an updated quote.</p>':''}
    ${pay&&!paid?'<button type="button" class="button payment-refresh">Refresh payment status</button>':''}
    ${!pay&&['REQUESTED','QUOTED','APPROVED'].includes(order.status)?`<details><summary>${address?'Change delivery address (requires a new shipping quote)':'Add delivery address'}</summary><form class="address-change"><div class="fields">${['name','line1','line2','city','state','postalCode'].map(k=>`<label>${esc({name:'Recipient',line1:'Street address',line2:'Apartment / suite',city:'City',state:'State (two letters)',postalCode:'ZIP code'}[k])}<input name="${k}" value="${esc(address?.[k]||'')}" maxlength="${k==='state'?2:180}" ${k==='line2'?'':'required'}></label>`).join('')}</div><button class="button" type="submit">Save delivery address</button></form></details>`:''}
    ${order.carrier?`<p><strong>${esc(order.carrier)}</strong> · ${esc(order.tracking)}</p>`:''}<details><summary>Order timeline</summary><ul>${order.timeline.map(t=>`<li>${esc(new Date(t.created_at*1000).toLocaleString())} · ${esc(t.customer_message)}</li>`).join('')}</ul></details><p class="message card-message" role="status"></p></article>`;
  }).join(''):'<p>Your first saved build will appear here.</p>';
    for(const card of $('orderList').querySelectorAll('[data-order]')){const o=orders.find(x=>x.id===card.dataset.order);
      card.querySelector('.approve')?.addEventListener('submit',e=>{e.preventDefault();cardAction(card,e.submitter,()=>api('business-approve',{orderId:o.id,revision:o.revision,proofId:o.proof.id,acceptQuote:true}),'Proof and quote approved.');});
      card.querySelector('.pay')?.addEventListener('submit',e=>{e.preventDefault();cardAction(card,e.submitter,async()=>{const result=await api('commerce-checkout',{orderId:o.id,offerVersion:o.commerce.offer.version,acceptTerms:true});const url=new URL(result.checkoutUrl);if(url.protocol!=='https:'||url.hostname!=='checkout.stripe.com')throw new Error('Secure checkout is unavailable.');location.assign(url.href);},'Opening secure checkout…',false);});
      card.querySelector('.payment-refresh')?.addEventListener('click',e=>cardAction(card,e.target,()=>api('commerce-refresh',{orderId:o.id}),'Payment status refreshed.'));
      card.querySelector('.address-change')?.addEventListener('submit',e=>{e.preventDefault();const address={...Object.fromEntries(new FormData(e.target)),country:'US'};cardAction(card,e.submitter,()=>api('commerce-address',{orderId:o.id,address}),'Delivery address saved. Shipping and production terms will be reviewed again.');});
    }
  }
  async function cardAction(card,button,action,success,refresh=true){button.disabled=true;const m=card.querySelector('.card-message');m.textContent='Saving…';try{await action();if(refresh)await refreshOrders();message('ordersMessage',success);}catch(error){m.textContent=error.message;m.classList.add('error');button.disabled=false;}}
  async function refreshOrders(){if(!session.authenticated||!session.capabilities.business){renderOrders();return;}const result=await api('business-orders');orders=result.orders.filter(o=>o.items.every(i=>allowed.includes(i.product)));renderOrders();}
  $('refreshOrders').addEventListener('click',async()=>{try{await refreshSession();await refreshOrders();message('ordersMessage','Orders refreshed.');}catch(error){message('ordersMessage',error.message,true);}});
  async function init(){loadDrafts();try{await refreshSession();await refreshOrders();const q=new URLSearchParams(location.search);if(q.get('payment')==='returned'){message('ordersMessage','Checking payment confirmation…');if(session.authenticated&&q.get('order')){await api('commerce-refresh',{orderId:q.get('order')});await refreshOrders();message('ordersMessage','Payment status checked. Only a confirmed payment is marked paid.');}else message('ordersMessage','Sign in to check your order’s confirmed payment status.');}if(q.get('payment')==='cancelled')message('ordersMessage','Checkout was closed. Your build remains saved; refresh its payment status before trying again.');}catch(error){message('ordersMessage',error.message,true);$('serviceStatus').textContent='Customer ordering is being connected. Your designs remain saved in this browser.';}}
  init();
})();
