const {test}=require('node:test');
const assert=require('node:assert/strict');
const E=require('../infinity-builder/engine.js');
const catalog=require('../infinity-builder/catalog.json');
function state(size=[24,24],rear='hub75',aspect=1,scale=65){const s=E.initial(catalog);s.size=size;s.rear=rear;s.artScale=scale;s.artwork={id:'orbit',name:'Orbital geometry',source:'library',approved:true,aspect};return s;}
test('three rim rows count separately and add an audio source only when selected',()=>{const s=state();s.rim.rows=3;s.rim.countPerRow=120;s.audioReactive=true;const p=E.plan(s,catalog);assert.equal(p.rimPixels,360);assert.ok(p.hardware.some(h=>h.id==='audio'));assert.ok(p.hardware.some(h=>h.id==='rim-controller'));s.audioReactive=false;assert.ok(!E.plan(s,catalog).hardware.some(h=>h.id==='audio'));});
test('all suggested layouts cover the engraving and physically fit inside each supported mirror',()=>{for(const size of catalog.sizes)for(const family of ['flex','hub75'])for(const aspect of [.4,1,2.5])for(const scale of [20,50,100]){const s=state(size,family,aspect,scale),box=E.artBox(s,catalog),room=E.interior(s,catalog);for(const p of E.candidates(s,catalog)){assert.ok(p.width+1e-7>=box.width);assert.ok(p.height+1e-7>=box.height);assert.ok(p.width<=room.width+1e-7);assert.ok(p.height<=room.height+1e-7);assert.equal(p.cells.length,p.count);for(const c of p.cells){assert.ok(c.x>=room.x-1e-7);assert.ok(c.y>=room.y-1e-7);assert.ok(c.x+c.width<=room.x+room.width+1e-7);assert.ok(c.y+c.height<=room.y+room.height+1e-7);}}}});
test('panel ranking minimizes unused area and checks both panel orientations',()=>{const s=state([20,20],'hub75',.45,55),ps=E.candidates(s,catalog);assert.ok(ps.length>0);assert.ok(ps.some(p=>p.rotated));for(let i=1;i<ps.length;i++)assert.ok(ps[i].unusedArea>=ps[i-1].unusedArea);});
test('a large rectangular HUB75 panel wins when the artwork coverage wastes less area',()=>{const s=state([30,30],'hub75',2,50);const ps=E.candidates(s,catalog);assert.ok(ps.some(p=>p.panelId==='hub-p5-64x32'));assert.equal(ps[0].unusedArea,Math.min(...ps.map(p=>p.unusedArea)));});
test('out of stock and insufficient stock panels are excluded',()=>{const c=structuredClone(catalog);c.panels.forEach(p=>p.stock=0);const s=state();assert.equal(E.candidates(s,c).length,0);assert.equal(E.plan(s,c).ready,false);c.panels[0].stock=1;assert.ok(E.candidates(s,c).every(p=>p.count<=1));});
test('unapproved artwork never produces a panel plan or a complete build',()=>{const s=state();s.artwork.approved=false;assert.equal(E.plan(s,catalog).layout,null);assert.equal(E.plan(s,catalog).ready,false);});
test('flexible and HUB75 controllers are incompatible; Beast remains unavailable',()=>{const s=state();s.controllerId='digi-quad';assert.equal(E.plan(s,catalog).controller.id,'matrixportal-s3');s.controllerId='beast';assert.equal(E.plan(s,catalog).controller.id,'matrixportal-s3');s.rear='flex';assert.deepEqual(E.controllers(s,catalog).map(c=>c.id),['digi-uno','digi-quad']);});
test('HUB75 does not acquire a fabricated power rating',()=>{const p=E.plan(state(),catalog);assert.equal(p.hub75PowerPending,true);assert.equal(p.addressableEstimateAmps,4.32);});
test('a build with neither rim nor rear LEDs cannot be completed',()=>{const s=state([12,12],'none');s.rim.enabled=false;assert.equal(E.plan(s,catalog).ready,false);});
